"""Auto-resolve weather shadow events from the keyless NWS observations API.

Resolves SHADOW-WX-<STATION>-HIGH-GT-<X>-<YYYYMMDD> events generated by
generate_weather_slate.py: Yes if the NWS observed daily maximum temperature at
the station on the (local) date is strictly greater than X degrees F.

Pulls the nearest observation station for each STATION code and takes the max
observed temperature over a window covering that local calendar day (observations
report Celsius; converted to F). Merges winners into resolutions.json without
clobbering manual/auto rows. --dry-run / --force.

Closes the loop for the Weather category, which mirrors a Prophet Arena event
class we previously had zero coverage of.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_weather_slate import STATIONS, POINTS, UA  # noqa: E402

RESOLUTIONS = Path("data/shadow_calibration/resolutions.json")
EVENTS = Path("data/shadow_calibration/events.json")


class FetchError(RuntimeError):
    pass


def _http_get(url: str, timeout: int = 25) -> str:
    proc = subprocess.run(
        ["curl", "-s", "--fail", "--max-time", str(timeout), "-H", f"User-Agent: {UA}", url],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise FetchError(f"curl exit {proc.returncode}: {proc.stderr.strip() or url}")
    return proc.stdout


def parse_spec(event: dict) -> dict | None:
    ticker = str(event.get("event_ticker") or "")
    parts = ticker.split("-")
    # SHADOW WX <STATION> HIGH GT <X> <YYYYMMDD>
    if len(parts) != 7 or parts[0] != "SHADOW" or parts[1] != "WX" or parts[3] != "HIGH" or parts[4] != "GT":
        return None
    station = parts[2]
    if station not in STATIONS:
        return None
    try:
        threshold = float(parts[5])
        date = datetime.strptime(parts[6], "%Y%m%d").date()
    except ValueError:
        return None
    return {"ticker": ticker, "station": station, "threshold": threshold,
            "date": date, "close_time": event.get("close_time")}


def observed_high_f(station: str, date) -> tuple[float | None, str]:
    """Max observed temperature (F) over the local calendar day, via NWS."""
    lat, lon, _label = STATIONS[station]
    pts = json.loads(_http_get(POINTS.format(lat=lat, lon=lon)))
    stations_url = pts["properties"]["observationStations"]
    st = json.loads(_http_get(stations_url))
    feats = st.get("features") or []
    if not feats:
        return None, "no observation station"
    station_id = feats[0]["properties"]["stationIdentifier"]
    # Window covers the local day across all contiguous-US offsets.
    start = f"{date.isoformat()}T08:00:00Z"
    end = (date + timedelta(days=1)).strftime("%Y-%m-%dT12:00:00Z")
    url = (f"https://api.weather.gov/stations/{station_id}/observations"
           f"?start={start}&end={end}")
    obs = json.loads(_http_get(url))
    temps_c = []
    for f in obs.get("features") or []:
        v = (((f.get("properties") or {}).get("temperature") or {}).get("value"))
        if isinstance(v, (int, float)):
            temps_c.append(v)
    if not temps_c:
        return None, f"no observations for {date} at {station_id}"
    max_f = max(temps_c) * 9.0 / 5.0 + 32.0
    return round(max_f, 1), f"{station_id} max {round(max(temps_c),1)}C = {round(max_f,1)}F"


def resolve_one(spec: dict) -> dict | None:
    try:
        high_f, note = observed_high_f(spec["station"], spec["date"])
    except (FetchError, ValueError, KeyError, IndexError) as exc:
        return {"_error": f"fetch failed: {exc}"}
    if high_f is None:
        return None  # observations not posted yet
    winner = "Yes" if high_f > spec["threshold"] else "No"
    return {
        "winner": winner,
        "resolved_at": spec["close_time"] or f"{spec['date'].isoformat()}T23:59:00Z",
        "observed": high_f,
        "source": "NWS observed daily high",
        "notes": f"auto-resolved: observed {high_f}F vs threshold {spec['threshold']}F ({note})",
        "auto_resolved_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--force", action="store_true", help="re-resolve rows that already exist")
    ap.add_argument("--events", type=Path, default=EVENTS)
    ap.add_argument("--resolutions", type=Path, default=RESOLUTIONS)
    args = ap.parse_args()

    events = json.loads(args.events.read_text())
    existing = json.loads(args.resolutions.read_text()) if args.resolutions.exists() else {}
    now = datetime.now(timezone.utc)

    resolved, pending, skipped = {}, [], []
    for event in events:
        spec = parse_spec(event)
        if spec is None:
            continue
        ticker = spec["ticker"]
        if ticker in existing and not args.force:
            skipped.append((ticker, "already resolved"))
            continue
        ct = spec.get("close_time")
        if ct:
            try:
                if datetime.fromisoformat(ct.replace("Z", "+00:00")) > now:
                    pending.append((ticker, f"closes {ct} (not yet)"))
                    continue
            except ValueError:
                pass
        rec = resolve_one(spec)
        if rec is None:
            pending.append((ticker, "no observations yet"))
        elif "_error" in rec:
            skipped.append((ticker, rec["_error"]))
        else:
            resolved[ticker] = rec

    print(f"weather scan at {now.isoformat()}\n")
    for t, r in sorted(resolved.items()):
        print(f"  RESOLVED  {t}  -> {r['winner']}  ({r['notes']})")
    for t, why in sorted(pending):
        print(f"  pending   {t}  ({why})")
    for t, why in sorted(skipped):
        print(f"  skipped   {t}  ({why})")
    print(f"\nnewly resolved: {len(resolved)}  pending: {len(pending)}  skipped: {len(skipped)}")

    if not resolved or args.dry_run:
        if args.dry_run and resolved:
            print("\n--dry-run: not writing.")
        elif not resolved:
            print("nothing to write.")
        return 0
    merged = dict(existing)
    merged.update(resolved)
    args.resolutions.write_text(json.dumps(merged, indent=2, sort_keys=True) + "\n")
    print(f"\nwrote {len(resolved)} resolution(s) to {args.resolutions}")
    print("next: python3 scripts/score_shadow_calibration.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
