#!/usr/bin/env bash
# Sync the project's .env file from the source-of-truth ~/Desktop/variables.txt
#
# Rob's workflow: he edits variables.txt; never .env directly. This script
# pulls only the keys the project needs into .env, preserves the comment
# header, and stays idempotent. Re-running it overwrites .env from the
# current variables.txt content -- intentional, since variables.txt is the
# authoritative source.
#
# Usage:
#   bash scripts/sync_env_from_variables.sh
#
# Safe to run repeatedly. Does not echo any secret values.

set -euo pipefail

SRC="$HOME/Desktop/variables.txt"
DST="$(cd "$(dirname "$0")/.." && pwd)/.env"

if [[ ! -f "$SRC" ]]; then
  echo "ERROR: $SRC does not exist" >&2
  exit 1
fi

# Keys we want to lift into .env. Add new ones here as the project grows.
KEYS=(
  PA_SERVER_API_KEY
  PA_SERVER_URL
  PA_TEAM_NAME
  OPENAI_API_KEY
  ANTHROPIC_API_KEY
)

# Build .env with a stable header + each key in order.
{
  cat <<'EOF'
# Prophet Hacks live config. Loaded by dotenv.
# This file is gitignored; never commit it.
#
# This file is GENERATED by scripts/sync_env_from_variables.sh from
# ~/Desktop/variables.txt. Hand-edits will be overwritten on the next run.
# Edit ~/Desktop/variables.txt instead.

EOF

  # PA_SERVER_URL has a sensible default if not in variables.txt.
  for key in "${KEYS[@]}"; do
    line="$(grep -E "^${key}=" "$SRC" || true)"
    if [[ -z "$line" ]]; then
      if [[ "$key" == "PA_SERVER_URL" ]]; then
        echo "PA_SERVER_URL=https://api.aiprophet.dev"
      else
        echo "# ${key} not found in variables.txt (skipped)"
      fi
    else
      echo "$line"
    fi
  done

  cat <<'EOF'

# Optional overrides (defaults shown):
# PROPHET_FORECAST_TRACK_MODEL=claude-sonnet-4-6
# PROPHET_FORECAST_OPUS_MODEL=claude-opus-4-7
# PROPHET_FORECAST_OPENAI_MODEL=gpt-5.5-pro
# PA_N_TICKS=96
EOF
} > "$DST"

# Print a one-line summary (no secrets).
present=()
missing=()
for key in "${KEYS[@]}"; do
  if grep -qE "^${key}=." "$DST"; then
    present+=("$key")
  else
    missing+=("$key")
  fi
done

echo "synced .env from $SRC"
echo "  present: ${present[*]}"
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "  missing or empty: ${missing[*]}"
fi
